### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by robahtou** [web-fountain/react-atx#2]
- [ ] add the media queries to transition to tablet/desktop views
- [ ] add javascript for button interactions with API
  - [ ] HAPPY PATH: user clicks on button and the form is submitted
- [ ] Continue to work the News Page
